services:
  client:
    image: gasreceiptclient:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    networks:
      - appNetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003"]
      interval: 30s
      timeout: 10s
      retries: 5
  server:
    image: gasreceiptserver:latest
    networks:
      - appNetwork
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env

networks:
  appNetwork:
    driver: bridge
    