services:
  client:
    image: gasreceiptclient:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    networks:
      - appNetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003"]
      interval: 30s
      timeout: 10s
      retries: 5
  server:
    image: gasreceiptserver:latest
    networks:
      - appNetwork
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env

  lubelogger:
    image: ghcr.io/hargata/lubelogger:latest
    restart: unless-stopped
    volumes:
      - lubelogger_data:/App/data
      - lubelogger_keys:/root/.aspnet/DataProtection-Keys
    ports:
      - "8080:8080"
    networks:
      - appNetwork

networks:
  appNetwork:
    driver: bridge

volumes:
  lubelogger_data:
  lubelogger_keys:
    